"""add conta_eliminada_em ao user

Revision ID: 4364402558ff
Revises: bc71c621b120
Create Date: 2026-08-22 07:32:50.260737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4364402558ff'
down_revision = 'bc71c621b120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_eliminada_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('conta_eliminada_em')

    # ### end Alembic commands ###
