"""add tags e moderação avançada da comunidade (fixado com prazo, suspensão de utilizadores)

Revision ID: 48f122c70c2d
Revises: 5571e6d9acc5
Create Date: 2026-08-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f122c70c2d'
down_revision = '5571e6d9acc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_tags_slug'), ['slug'], unique=True)

    op.create_table('comunidade_post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['comunidade_posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['comunidade_tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )

    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixado_ate', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comunidade_banido', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comunidade_suspenso_ate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('comunidade_suspensao_motivo', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('comunidade_suspensao_motivo')
        batch_op.drop_column('comunidade_suspenso_ate')
        batch_op.drop_column('comunidade_banido')

    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.drop_column('fixado_ate')

    op.drop_table('comunidade_post_tags')
    with op.batch_alter_table('comunidade_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_tags_slug'))

    op.drop_table('comunidade_tags')
    # ### end Alembic commands ###
