"""add grupo_upload to materiais

Revision ID: 4d5c17ddbfb8
Revises: d626ff37f8c4
Create Date: 2026-05-10 15:44:24.353040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5c17ddbfb8'
down_revision = 'd626ff37f8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_upload', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_materiais_grupo_upload'), ['grupo_upload'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiais_grupo_upload'))
        batch_op.drop_column('grupo_upload')

    # ### end Alembic commands ###
