"""configuracoes lista_espera relatorios_materiais

Revision ID: 500deed39296
Revises: ddec3667c722
Create Date: 2026-05-24 11:51:55.251144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500deed39296'
down_revision = 'ddec3667c722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('lista_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lista_espera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lista_espera_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lista_espera_status'), ['status'], unique=False)

    op.create_table('relatorios_materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relatorios_materiais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relatorios_materiais_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios_materiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relatorios_materiais_status'))

    op.drop_table('relatorios_materiais')
    with op.batch_alter_table('lista_espera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lista_espera_status'))
        batch_op.drop_index(batch_op.f('ix_lista_espera_email'))

    op.drop_table('lista_espera')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
