"""add tabelas de comunidade (posts, respostas, votos, relatorios)

Revision ID: 5571e6d9acc5
Revises: b3e90186eb0a
Create Date: 2026-08-20 23:10:25.970924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5571e6d9acc5'
down_revision = 'b3e90186eb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('fixado', sa.Boolean(), nullable=False),
    sa.Column('respostas_count', sa.Integer(), nullable=False),
    sa.Column('votos_score', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_posts_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_posts_votos_score'), ['votos_score'], unique=False)

    op.create_table('comunidade_relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=20), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_relatorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_relatorios_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_relatorios_status'), ['status'], unique=False)

    op.create_table('comunidade_votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=20), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilizador_id', 'alvo_tipo', 'alvo_id', name='uq_voto_user_alvo')
    )
    with op.batch_alter_table('comunidade_votos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_votos_alvo_id'), ['alvo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_votos_utilizador_id'), ['utilizador_id'], unique=False)

    op.create_table('comunidade_post_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('path_relativo', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['comunidade_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_post_imagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_post_imagens_post_id'), ['post_id'], unique=False)

    op.create_table('comunidade_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('votos_score', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['comunidade_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_respostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_respostas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_respostas_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_respostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_respostas_post_id'))
        batch_op.drop_index(batch_op.f('ix_comunidade_respostas_criado_em'))

    op.drop_table('comunidade_respostas')
    with op.batch_alter_table('comunidade_post_imagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_post_imagens_post_id'))

    op.drop_table('comunidade_post_imagens')
    with op.batch_alter_table('comunidade_votos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_votos_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_comunidade_votos_alvo_id'))

    op.drop_table('comunidade_votos')
    with op.batch_alter_table('comunidade_relatorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_relatorios_status'))
        batch_op.drop_index(batch_op.f('ix_comunidade_relatorios_criado_em'))

    op.drop_table('comunidade_relatorios')
    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_posts_votos_score'))
        batch_op.drop_index(batch_op.f('ix_comunidade_posts_criado_em'))

    op.drop_table('comunidade_posts')
    # ### end Alembic commands ###
