"""add tabela de imagens das respostas da comunidade

Revision ID: 65eeaa555af3
Revises: 4364402558ff
Create Date: 2026-08-22 08:00:43.642855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65eeaa555af3'
down_revision = '4364402558ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade_resposta_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta_id', sa.Integer(), nullable=False),
    sa.Column('path_relativo', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resposta_id'], ['comunidade_respostas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_resposta_imagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_resposta_imagens_resposta_id'), ['resposta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_resposta_imagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_resposta_imagens_resposta_id'))

    op.drop_table('comunidade_resposta_imagens')
    # ### end Alembic commands ###
