"""add banner_key to anuncios

Revision ID: 6f163ebeeb7d
Revises: a74177ba4432
Create Date: 2026-05-30 15:13:22.067218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f163ebeeb7d'
down_revision = 'a74177ba4432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_key', sa.String(length=500), nullable=True))
        batch_op.alter_column('banner_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.alter_column('banner_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('banner_key')

    # ### end Alembic commands ###
