"""add notificacoes table

Revision ID: 7657dc45d768
Revises: 81a234b27c7a
Create Date: 2026-05-11 22:22:04.885179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7657dc45d768'
down_revision = '81a234b27c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_criado_em'), ['criado_em'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_criado_em'))

    op.drop_table('notificacoes')
    # ### end Alembic commands ###
