"""comunidade: replicas de respostas (1 nivel) e revisao proativa de posts

Revision ID: 79f217b72e36
Revises: 48f122c70c2d
Create Date: 2026-08-21 23:33:24.356889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f217b72e36'
down_revision = '48f122c70c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revisto', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('revisto_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revisto_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comunidade_posts_revisto'), ['revisto'], unique=False)
        batch_op.create_foreign_key('fk_comunidade_posts_revisto_por_id_users', 'users', ['revisto_por_id'], ['id'])

    with op.batch_alter_table('comunidade_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comunidade_respostas_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_comunidade_respostas_parent_id_comunidade_respostas', 'comunidade_respostas', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_respostas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comunidade_respostas_parent_id_comunidade_respostas', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comunidade_respostas_parent_id'))
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comunidade_posts_revisto_por_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comunidade_posts_revisto'))
        batch_op.drop_column('revisto_em')
        batch_op.drop_column('revisto_por_id')
        batch_op.drop_column('revisto')

    # ### end Alembic commands ###
