"""add pastas table and pasta_id em materiais

Revision ID: 7b3deb02f479
Revises: cee265405a3c
Create Date: 2026-08-20 18:17:38.019678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3deb02f479'
down_revision = 'cee265405a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pastas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pastas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pastas_caminho'), ['caminho'], unique=False)
        batch_op.create_index(batch_op.f('ix_pastas_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_pastas_parent_id'), ['parent_id'], unique=False)

    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasta_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_materiais_pasta_id'), ['pasta_id'], unique=False)
        batch_op.create_foreign_key('fk_materiais_pasta_id_pastas', 'pastas', ['pasta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materiais_pasta_id_pastas', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_materiais_pasta_id'))
        batch_op.drop_column('pasta_id')

    with op.batch_alter_table('pastas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pastas_parent_id'))
        batch_op.drop_index(batch_op.f('ix_pastas_criado_em'))
        batch_op.drop_index(batch_op.f('ix_pastas_caminho'))

    op.drop_table('pastas')
    # ### end Alembic commands ###
