"""add ficheiro_hash to materiais

Revision ID: 9345e00cf91e
Revises: 7657dc45d768
Create Date: 2026-05-11 23:56:21.573345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9345e00cf91e'
down_revision = '7657dc45d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ficheiro_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_materiais_ficheiro_hash'), ['ficheiro_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiais_ficheiro_hash'))
        batch_op.drop_column('ficheiro_hash')

    # ### end Alembic commands ###
