"""Add candidaturas table

Revision ID: a6ca14208819
Revises: 6f163ebeeb7d
Create Date: 2026-07-27 00:39:17.363893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ca14208819'
down_revision = '6f163ebeeb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('universidade', sa.String(length=100), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('ano', sa.String(length=50), nullable=True),
    sa.Column('contribuicoes', sa.Text(), nullable=True),
    sa.Column('motivacao', sa.Text(), nullable=True),
    sa.Column('impacto', sa.Text(), nullable=True),
    sa.Column('experiencia', sa.Text(), nullable=True),
    sa.Column('lideranca', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('lideranca_motivo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidaturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidaturas_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidaturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidaturas_email'))

    op.drop_table('candidaturas')
    # ### end Alembic commands ###
