"""add tabela anuncios

Revision ID: a74177ba4432
Revises: 500deed39296
Create Date: 2026-05-30 14:14:17.704640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74177ba4432'
down_revision = '500deed39296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anunciante', sa.String(length=120), nullable=False),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=False),
    sa.Column('link_destino', sa.String(length=500), nullable=True),
    sa.Column('percentagem', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncios')
    # ### end Alembic commands ###
