"""add aceita_marketing e campanhas de email

Revision ID: b3e90186eb0a
Revises: 7b3deb02f479
Create Date: 2026-08-20 22:28:43.036452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e90186eb0a'
down_revision = '7b3deb02f479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanhas_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('corpo_html', sa.Text(), nullable=False),
    sa.Column('publico', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('total_destinatarios', sa.Integer(), nullable=False),
    sa.Column('enviados', sa.Integer(), nullable=False),
    sa.Column('falhados', sa.Integer(), nullable=False),
    sa.Column('enviados_hoje', sa.Integer(), nullable=False),
    sa.Column('data_ultimo_envio', sa.Date(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campanhas_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campanhas_email_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_campanhas_email_estado'), ['estado'], unique=False)

    op.create_table('campanha_email_destinatarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas_email.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campanha_id', 'utilizador_id', name='uq_campanha_utilizador')
    )
    with op.batch_alter_table('campanha_email_destinatarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campanha_email_destinatarios_campanha_id'), ['campanha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campanha_email_destinatarios_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_campanha_email_destinatarios_utilizador_id'), ['utilizador_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default garante que utilizadores já existentes ficam com
        # aceita_marketing=True (podem cancelar depois), em vez de a coluna
        # NOT NULL falhar por não ter valor para as linhas já existentes.
        batch_op.add_column(sa.Column('aceita_marketing', sa.Boolean(), nullable=False, server_default=sa.true()))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('aceita_marketing', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('aceita_marketing')

    with op.batch_alter_table('campanha_email_destinatarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campanha_email_destinatarios_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_campanha_email_destinatarios_estado'))
        batch_op.drop_index(batch_op.f('ix_campanha_email_destinatarios_campanha_id'))

    op.drop_table('campanha_email_destinatarios')
    with op.batch_alter_table('campanhas_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campanhas_email_estado'))
        batch_op.drop_index(batch_op.f('ix_campanhas_email_criado_em'))

    op.drop_table('campanhas_email')
    # ### end Alembic commands ###
