"""add tabela visita_log para estatisticas de trafego anonimo

Revision ID: bc71c621b120
Revises: 79f217b72e36
Create Date: 2026-08-21 23:39:12.371197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc71c621b120'
down_revision = '79f217b72e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.String(length=36), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('caminho', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visita_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visita_log_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_visita_log_sessao_id'), ['sessao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visita_log_utilizador_id'), ['utilizador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visita_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visita_log_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_visita_log_sessao_id'))
        batch_op.drop_index(batch_op.f('ix_visita_log_criado_em'))

    op.drop_table('visita_log')
    # ### end Alembic commands ###
