"""add atividade_log table

Revision ID: cee265405a3c
Revises: a6ca14208819
Create Date: 2026-08-20 17:36:09.307708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee265405a3c'
down_revision = 'a6ca14208819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=40), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('alvo_tipo', sa.String(length=40), nullable=True),
    sa.Column('alvo_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atividade_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividade_log_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_atividade_log_evento'), ['evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_atividade_log_utilizador_id'), ['utilizador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividade_log_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_atividade_log_evento'))
        batch_op.drop_index(batch_op.f('ix_atividade_log_criado_em'))

    op.drop_table('atividade_log')
    # ### end Alembic commands ###
