"""init

Revision ID: d626ff37f8c4
Revises: 
Create Date: 2026-05-09 17:15:31.754327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd626ff37f8c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('curso', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=300), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('total_uploads', sa.Integer(), nullable=True),
    sa.Column('total_downloads', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('instituicao', sa.String(length=200), nullable=False),
    sa.Column('curso', sa.String(length=200), nullable=True),
    sa.Column('disciplina', sa.String(length=200), nullable=False),
    sa.Column('ano_letivo', sa.String(length=10), nullable=True),
    sa.Column('ano_escolar', sa.String(length=20), nullable=True),
    sa.Column('semestre', sa.String(length=10), nullable=True),
    sa.Column('ficheiro_nome', sa.String(length=300), nullable=False),
    sa.Column('ficheiro_path', sa.String(length=500), nullable=False),
    sa.Column('ficheiro_tipo', sa.String(length=10), nullable=True),
    sa.Column('ficheiro_tamanho', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('moderado_por_id', sa.Integer(), nullable=True),
    sa.Column('visualizacoes', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('nota_media', sa.Float(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['moderado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiais_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiais_curso'), ['curso'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiais_disciplina'), ['disciplina'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiais_instituicao'), ['instituicao'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiais_status'), ['status'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilizador_id', 'material_id', name='uq_avaliacao_user_material')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiais_status'))
        batch_op.drop_index(batch_op.f('ix_materiais_instituicao'))
        batch_op.drop_index(batch_op.f('ix_materiais_disciplina'))
        batch_op.drop_index(batch_op.f('ix_materiais_curso'))
        batch_op.drop_index(batch_op.f('ix_materiais_criado_em'))

    op.drop_table('materiais')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('categorias')
    # ### end Alembic commands ###
