"""kpi pesquisa_log e moderador no user

Revision ID: ddec3667c722
Revises: 9345e00cf91e
Create Date: 2026-05-12 21:46:43.850753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddec3667c722'
down_revision = '9345e00cf91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesquisa_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termo', sa.String(length=300), nullable=False),
    sa.Column('n_resultados', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesquisa_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pesquisa_log_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_pesquisa_log_termo'), ['termo'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moderador', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_moderador')

    with op.batch_alter_table('pesquisa_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pesquisa_log_termo'))
        batch_op.drop_index(batch_op.f('ix_pesquisa_log_criado_em'))

    op.drop_table('pesquisa_log')
    # ### end Alembic commands ###
