"""add reacoes, ligacoes internas e audit log da comunidade

Revision ID: e390e8b34e5b
Revises: ea7263fae1c2
Create Date: 2026-08-22 12:43:10.173649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e390e8b34e5b'
down_revision = 'ea7263fae1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload_before', sa.JSON(), nullable=True),
    sa.Column('payload_after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_audit_log_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('comunidade_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_tipo', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_tipo', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_tipo', 'source_id', 'target_tipo', 'target_id', name='uq_link_source_target')
    )
    with op.batch_alter_table('comunidade_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_links_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_comunidade_links_source', ['source_tipo', 'source_id'], unique=False)
        batch_op.create_index('ix_comunidade_links_target', ['target_tipo', 'target_id'], unique=False)

    op.create_table('comunidade_reacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=20), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilizador_id', 'alvo_tipo', 'alvo_id', 'tipo', name='uq_reacao_user_alvo_tipo')
    )
    with op.batch_alter_table('comunidade_reacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_reacoes_alvo_id'), ['alvo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_reacoes_utilizador_id'), ['utilizador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_reacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_reacoes_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_comunidade_reacoes_alvo_id'))

    op.drop_table('comunidade_reacoes')
    with op.batch_alter_table('comunidade_links', schema=None) as batch_op:
        batch_op.drop_index('ix_comunidade_links_target')
        batch_op.drop_index('ix_comunidade_links_source')
        batch_op.drop_index(batch_op.f('ix_comunidade_links_criado_em'))

    op.drop_table('comunidade_links')
    with op.batch_alter_table('comunidade_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_comunidade_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_comunidade_audit_log_criado_em'))
        batch_op.drop_index(batch_op.f('ix_comunidade_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_comunidade_audit_log_action'))

    op.drop_table('comunidade_audit_log')
    # ### end Alembic commands ###
