"""add subscricoes de topicos na comunidade

Revision ID: ea7263fae1c2
Revises: fdfa8bb37df0
Create Date: 2026-08-22 12:33:13.176273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7263fae1c2'
down_revision = 'fdfa8bb37df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade_subscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['comunidade_posts.id'], ),
    sa.ForeignKeyConstraint(['utilizador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilizador_id', 'post_id', name='uq_subscricao_user_post')
    )
    with op.batch_alter_table('comunidade_subscricoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_subscricoes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_subscricoes_utilizador_id'), ['utilizador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_subscricoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_subscricoes_utilizador_id'))
        batch_op.drop_index(batch_op.f('ix_comunidade_subscricoes_post_id'))

    op.drop_table('comunidade_subscricoes')
    # ### end Alembic commands ###
