"""categorias, estados, melhor resposta e edicao na comunidade

Revision ID: fdfa8bb37df0
Revises: 65eeaa555af3
Create Date: 2026-08-22 08:05:37.191486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfa8bb37df0'
down_revision = '65eeaa555af3'
branch_labels = None
depends_on = None


# Categorias por omissão (ver spec da Comunidade) — slug é a chave estável
# usada para o backfill abaixo, nunca a mostrar ao utilizador.
CATEGORIAS_SEED = [
    dict(slug='anuncios', nome='Anúncios', descricao='Comunicados oficiais da equipa.',
         icone='bi-patch-check-fill', ordem=0, apenas_admin=True, ativa=True),
    dict(slug='duvidas', nome='Dúvidas', descricao='Perguntas sobre matérias, exercícios e provas.',
         icone='bi-question-circle', ordem=1, apenas_admin=False, ativa=True),
    dict(slug='pedidos-material', nome='Pedidos de Material', descricao='Pede um material que ainda não existe na plataforma.',
         icone='bi-search', ordem=2, apenas_admin=False, ativa=True),
    dict(slug='partilhas', nome='Partilhas', descricao='Partilha dicas, recursos e experiências.',
         icone='bi-share', ordem=3, apenas_admin=False, ativa=True),
    dict(slug='geral', nome='Geral', descricao='Conversa livre entre estudantes.',
         icone='bi-chat-dots', ordem=4, apenas_admin=False, ativa=True),
]

# tipo (enum antigo) -> slug da categoria equivalente, para não deixar os
# posts já existentes sem categoria.
MAPA_TIPO_SLUG = {'aviso': 'anuncios', 'duvida': 'duvidas', 'discussao': 'geral'}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('apenas_admin', sa.Boolean(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunidade_categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunidade_categorias_slug'), ['slug'], unique=True)

    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        # server_default só para as linhas já existentes ganharem um valor válido
        # nesta migração — o default "de verdade" para posts novos é o do model.
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False, server_default='aberto'))
        batch_op.add_column(sa.Column('editado', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('melhor_resposta_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comunidade_posts_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunidade_posts_estado'), ['estado'], unique=False)
        batch_op.create_foreign_key('fk_comunidade_posts_melhor_resposta_id', 'comunidade_respostas', ['melhor_resposta_id'], ['id'])
        batch_op.create_foreign_key('fk_comunidade_posts_categoria_id', 'comunidade_categorias', ['categoria_id'], ['id'])

    with op.batch_alter_table('comunidade_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editado', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###

    # ── Dados: semear as categorias por omissão e migrar os posts existentes
    #    do antigo `tipo` para a categoria equivalente ──────────────────────
    categorias_tbl = sa.table(
        'comunidade_categorias',
        sa.column('id', sa.Integer), sa.column('slug', sa.String), sa.column('nome', sa.String),
        sa.column('descricao', sa.String), sa.column('icone', sa.String), sa.column('ordem', sa.Integer),
        sa.column('apenas_admin', sa.Boolean), sa.column('ativa', sa.Boolean),
    )
    posts_tbl = sa.table(
        'comunidade_posts', sa.column('id', sa.Integer), sa.column('tipo', sa.String),
        sa.column('categoria_id', sa.Integer),
    )

    conn = op.get_bind()
    conn.execute(sa.insert(categorias_tbl), CATEGORIAS_SEED)

    for tipo, slug in MAPA_TIPO_SLUG.items():
        cat_id = conn.execute(sa.select(categorias_tbl.c.id).where(categorias_tbl.c.slug == slug)).scalar()
        if cat_id:
            conn.execute(posts_tbl.update().where(posts_tbl.c.tipo == tipo).values(categoria_id=cat_id))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunidade_respostas', schema=None) as batch_op:
        batch_op.drop_column('editado')

    with op.batch_alter_table('comunidade_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comunidade_posts_categoria_id', type_='foreignkey')
        batch_op.drop_constraint('fk_comunidade_posts_melhor_resposta_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comunidade_posts_estado'))
        batch_op.drop_index(batch_op.f('ix_comunidade_posts_categoria_id'))
        batch_op.drop_column('melhor_resposta_id')
        batch_op.drop_column('editado')
        batch_op.drop_column('estado')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('comunidade_categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunidade_categorias_slug'))

    op.drop_table('comunidade_categorias')
    # ### end Alembic commands ###
